version: 2
jobs:
  build:
    docker:
      - image: zondax/qrl-build-images:xenial
    steps:
      - checkout
      - run: pip install -U setuptools
      - run: pip install -U -r requirements.txt
      - run: pip install -U -r test-requirements.txt
      - run: python3 setup.py test --addopts "--cov . --cov-report term-missing --cov-report xml"
      - run: sudo pip install -U coverage codacy-coverage
      - run: if [[ "$TRAVIS_BRANCH" == "master" ]]; then python-codacy-coverage -r coverage.xml || echo "failed"; fi

workflows:
  version: 2
  build_all:
    jobs:
      - build
